name: "Lint Python code"
on:
  push: # Only execute pipeline when someone pushes a commit to these branches
    -master
  pull_request:
    -master
jobs:
  lint: # Name of the job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install ruff
      - name: Lint the project
        run: ruff check --output-format=github