name: "Deploy webpage"
on:
  push: # Only execute pipeline when someone pushes a commmit to these branches
    branches:
      - master


jobs:
  pages: # Name of the job
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create artifact
        run: |
          mkdir -p public
          mv index.html public/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 
            ./public
      - id: deployment
        uses: actions/deploy-pages@v4